---
- name: install softwares in windows server
  hosts: all
  become: yes
  tasks:
    - name: install softwares
      win_chocolatey:
        name:
          - git
          - vscode
        state: present