---
- name: Install tomcat 10 on ubuntu 22
  hosts: appservers
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.package:
        name: "{{ java_package_name }}"
        state: present