---
- name: install utilities
  hosts: all
  tasks:
    - name: install utilities
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      become: yes
      loop: "{{ packages }}"
    - name: debug variable
      ansible.builtin.debug:
        var: purpose
    - name: the configuration file of ansible
      ansible.builtin.debug:
        var: ansible_config_file
        