---
- name: install utilities
  hosts: all
  become: yes
  tasks:
    - name: install tree on ubuntu
      ansible.builtin.apt:
        name: tree
        update_cache: yes
        state: present
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present


- name: install servers