---
- name: install apache
  become: yes
  hosts: all
  tasks:
    - name: update packages and install apache
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: present
      when: ansible_facts['os_family'] == 'Debian'
    - name: install httpd
      ansible.builtin.dnf:
        name: "{{ package_name }}"
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
    - name: enable and start httpd
      ansible.builtin.systemd_service:
        name: "{{ package_name }}"
        enabled: yes
        state: started
