---
- name: install apache
  become: yes
  hosts: all
  tasks:
    - name: install httpd
      package:
        name: "{{ package_name }}"
        state: present
    - name: enable and start httpd
      ansible.builtin.systemd_service:
        name: "{{ package_name }}"
        enabled: yes
        state: started
