- name: update packages and install java
  ansible.builtin.yum:
    name: java-11-openjdk
    state: present
  when: ansible_facts['os_family'] == "RedHat"
- ansible.builtin.debug:
    msg: "java is installed using package java-11-openjdk"